//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int id { get; set; }
        public string description { get; set; }
        public string img_url { get; set; }
        public string status { get; set; }
        public Nullable<int> transaction_id { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
