//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class election_list_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public election_list_request()
        {
            this.candidate_request = new HashSet<candidate_request>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> district_id { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string image_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidate_request> candidate_request { get; set; }
        public virtual district district { get; set; }
    }
}
