//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeProjectMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class electionEntities : DbContext
    {
        public electionEntities()
            : base("name=electionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<candidate_request> candidate_request { get; set; }
        public virtual DbSet<contact_us> contact_us { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<debate> debates { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<election_list> election_list { get; set; }
        public virtual DbSet<election_list_request> election_list_request { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<voter_user> voter_user { get; set; }
    }
}
