//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voter_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voter_user()
        {
            this.candidates = new HashSet<candidate>();
            this.candidate_request = new HashSet<candidate_request>();
        }
    
        public int id { get; set; }
        public string national_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int district_id { get; set; }
        public System.DateTime birth_date { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string ethnicity { get; set; }
        public bool has_locally_voted { get; set; }
        public bool has_party_voted { get; set; }
        public bool first_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidate> candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidate_request> candidate_request { get; set; }
        public virtual district district { get; set; }
    }
}
